/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import com.myctu.touristmanagementsystem.model.ChuDichVu;
import com.myctu.touristmanagementsystem.model.LocaleManager;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class ChinhSuaHoSoAdminVew extends javax.swing.JPanel {

    /**
     * Creates new form ChinhSuaHoSoAdmin
     */
    public ChinhSuaHoSoAdminVew() {
        initComponents();
        customizeView();
        locale();
    }

      private ResourceBundle rb;

    private void locale() {
//        Locale.setDefault(locale); // Đặt locale mặc định
        try {
            rb = ResourceBundle.getBundle("com.myctu.touristmanagementsystem.properties.MyResources", LocaleManager.getCurrentLocale());
            System.out.println("Resource bundle loaded successfully.");
            setText(); // Cập nhật giao diện với ngôn ngữ mới
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
//        JComboBox<String> languageComboBox = new JComboBox<>(new String[]{"Tiếng Việt", "English"});
//        this.btnChange = languageComboBox;
    }

    private void setText() {
        //thong tin tai khoan
        lbThongTinTaiKhoan.setText(rb.getString("infoAccount"));
        lbHoVaTen.setText(rb.getString("full_name"));
        lbEmail.setText(rb.getString("email"));
        lbSosDienThoai.setText(rb.getString("phone"));
        btnCapNhatThongTinTaiKhoan.setText(rb.getString("updateAccount"));
    }

    private void customizeView() {
        addIcon();
        //Cai tooltip        
        setEditProfile(false);
        lbToolTip.setOpaque(true); // Đảm bảo JLabel có nền
        lbToolTip.setBackground(Color.WHITE); // Màu nền của tooltip
        lbToolTip.setVisible(false); // Ẩn tooltip khi khởi tạo
    }

    public void setToolTip(Boolean bol) {
        lbToolTip.setVisible(bol);
    }

    private void addIcon() {
        ImageIcon imgChinhSuaHoSo = new ImageIcon(getClass().getResource("/com/myctu/touristmanagementsystem/img/user-avatar.png"));
        Image resizedImageChinhSuaHoSo = imgChinhSuaHoSo.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        ImageIcon newIconChinhSuHoSo = new ImageIcon(resizedImageChinhSuaHoSo);
        btnChinhSuaHoSo.setBackground(Color.WHITE);
        btnChinhSuaHoSo.setIcon(newIconChinhSuHoSo);
    }

    public void setEditProfile(Boolean bool) {
        if (bool) {
            tfHoVaTen.setEditable(true);
            tfEmail.setEditable(true);
            tfSoDienThoai.setEditable(true);
            btnCapNhatThongTinTaiKhoan.setEnabled(true);
        } else {
            tfHoVaTen.setEditable(false);
            tfEmail.setEditable(false);
            tfSoDienThoai.setEditable(false);
            btnCapNhatThongTinTaiKhoan.setEnabled(false);
        }
    }

    public ChuDichVu getThongTinTaiKhoan() {
        ChuDichVu cdv = null;
        String hoVaTen = tfHoVaTen.getText().trim();
        String email = tfEmail.getText().trim();
        String sdt = tfSoDienThoai.getText().trim();
        cdv = new ChuDichVu(hoVaTen, email, sdt);
        return cdv;
    }

    public void setThongTinTaiKhoan(ChuDichVu cdv) {
        System.out.println("Đang thiết lập thông tin tài khoản cho: " + cdv.getHoVaTen());
        tfHoVaTen.setText(cdv.getHoVaTen());
        tfEmail.setText(cdv.getEmail());
        tfSoDienThoai.setText(cdv.getSoDienThoai());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbThongTinTaiKhoan = new javax.swing.JLabel();
        lbBackGround = new javax.swing.JLabel();
        pnThongTin = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        tfHoVaTen = new javax.swing.JTextField();
        lbSosDienThoai = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbHoVaTen = new javax.swing.JLabel();
        tfSoDienThoai = new javax.swing.JTextField();
        btnCapNhatThongTinTaiKhoan = new javax.swing.JButton();
        lbToolTip = new javax.swing.JLabel();
        btnChinhSuaHoSo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setLayout(null);

        lbThongTinTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbThongTinTaiKhoan.setForeground(new java.awt.Color(102, 102, 102));
        lbThongTinTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongTinTaiKhoan.setText("Thông tin tài khoản");
        add(lbThongTinTaiKhoan);
        lbThongTinTaiKhoan.setBounds(212, 40, 780, 61);

        lbBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myctu/touristmanagementsystem/img/profile-background-2ozk94drrgrfpa5u.jpg"))); // NOI18N
        lbBackGround.setOpaque(true);
        add(lbBackGround);
        lbBackGround.setBounds(-7, -7, 1210, 140);

        pnThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfEmail.setMargin(new java.awt.Insets(2, 10, 2, 6));
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        tfHoVaTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfHoVaTen.setMargin(new java.awt.Insets(2, 10, 2, 6));
        tfHoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoVaTenActionPerformed(evt);
            }
        });

        lbSosDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbSosDienThoai.setText("Số điện thoại");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setText("Email");

        lbHoVaTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHoVaTen.setText("Họ và tên");

        tfSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSoDienThoai.setMargin(new java.awt.Insets(2, 10, 2, 6));
        tfSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoDienThoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinLayout = new javax.swing.GroupLayout(pnThongTin);
        pnThongTin.setLayout(pnThongTinLayout);
        pnThongTinLayout.setHorizontalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoVaTen)
                    .addComponent(lbEmail)
                    .addComponent(lbSosDienThoai))
                .addGap(48, 48, 48)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfHoVaTen)
                    .addComponent(tfEmail)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );
        pnThongTinLayout.setVerticalGroup(
            pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSosDienThoai)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        add(pnThongTin);
        pnThongTin.setBounds(250, 210, 680, 240);

        btnCapNhatThongTinTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        btnCapNhatThongTinTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhatThongTinTaiKhoan.setText("Cập nhật thông tin tài khoản");
        btnCapNhatThongTinTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatThongTinTaiKhoanActionPerformed(evt);
            }
        });
        add(btnCapNhatThongTinTaiKhoan);
        btnCapNhatThongTinTaiKhoan.setBounds(490, 510, 290, 40);

        lbToolTip.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lbToolTip.setText("click here to edit");
        add(lbToolTip);
        lbToolTip.setBounds(980, 240, 100, 14);

        btnChinhSuaHoSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinhSuaHoSoActionPerformed(evt);
            }
        });
        add(btnChinhSuaHoSo);
        btnChinhSuaHoSo.setBounds(950, 210, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void tfHoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoVaTenActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoDienThoaiActionPerformed

    private void btnChinhSuaHoSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinhSuaHoSoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChinhSuaHoSoActionPerformed

    private void btnCapNhatThongTinTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatThongTinTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapNhatThongTinTaiKhoanActionPerformed

    public void addButtonChinhSuaListener(ActionListener listener, MouseListener mouseListener) {
        btnChinhSuaHoSo.addActionListener(listener);
        btnChinhSuaHoSo.addMouseListener(mouseListener);
    }

    public void addButtonCapNhatTaiKhoanListener(ActionListener listener) {
        btnCapNhatThongTinTaiKhoan.addActionListener(listener);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatThongTinTaiKhoan;
    private javax.swing.JButton btnChinhSuaHoSo;
    private javax.swing.JLabel lbBackGround;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHoVaTen;
    private javax.swing.JLabel lbSosDienThoai;
    private javax.swing.JLabel lbThongTinTaiKhoan;
    private javax.swing.JLabel lbToolTip;
    private javax.swing.JPanel pnThongTin;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHoVaTen;
    private javax.swing.JTextField tfSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
