/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import com.myctu.touristmanagementsystem.model.DanhSachDatTourTableModelInAd;
import com.myctu.touristmanagementsystem.model.LocaleManager;
import java.awt.event.ActionListener;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ASUS
 */
public class DanhSachDatTour extends javax.swing.JPanel {

    /**
     * Creates new form DanhSachDatTour
     */
    public DanhSachDatTour() {
        initComponents();
        locale();
    }

        private ResourceBundle rb;

    private void locale() {
//        Locale.setDefault(); // Đặt locale mặc định
        try {
            rb = ResourceBundle.getBundle("com.myctu.touristmanagementsystem.properties.MyResources", LocaleManager.getCurrentLocale());
            System.out.println("Resource bundle loaded successfully.");
            setText();
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
    }

    private void setText() {
        try {
            lbDSDatTour.setText(rb.getString("bookingList"));
            btnTimKiem.setText(rb.getString("search"));
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbChiTiet = new javax.swing.JTable();
        tfTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lbDSDatTour = new javax.swing.JLabel();
        lbNenDSDatTour = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 242, 245));
        setPreferredSize(new java.awt.Dimension(1200, 650));
        setLayout(null);

        tbChiTiet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số", "Tên người đặt", "Tên tour", "Số lượng", "Thời gian", "Tổng số tiền"
            }
        ));
        jScrollPane1.setViewportView(tbChiTiet);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 190, 890, 420);

        tfTimKiem.setText("Tìm kiếm theo tên tour");
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });
        add(tfTimKiem);
        tfTimKiem.setBounds(410, 130, 340, 40);

        btnTimKiem.setBackground(new java.awt.Color(51, 153, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        add(btnTimKiem);
        btnTimKiem.setBounds(770, 130, 90, 40);

        lbDSDatTour.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbDSDatTour.setForeground(new java.awt.Color(51, 51, 51));
        lbDSDatTour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDSDatTour.setText("Danh sách đặt dịch vụ");
        add(lbDSDatTour);
        lbDSDatTour.setBounds(390, 20, 400, 50);

        lbNenDSDatTour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myctu/touristmanagementsystem/img/Background-trang-xanh.jpg"))); // NOI18N
        add(lbNenDSDatTour);
        lbNenDSDatTour.setBounds(0, 0, 1200, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

//code table
    public void setTableModel(DanhSachDatTourTableModelInAd tableModel) {
        tbChiTiet.setModel(tableModel);
    }

//    public void fillInputForm() {
//        int row = tbChiTiet.getSelectedRow();
//
//        if (row >= 0) {
////            tfId.setText(tbDanhSachDichVu.getValueAt(row, 0).toString());
////            tfProductName.setText(tbDanhSachDichVu.getValueAt(row, 1).toString());
//            tfMoTa.setText(tbDanhSachDichVu.getValueAt(row, 2).toString());
//        }
//    }
    public void addTableSelecctionListener(ListSelectionListener listener) {
        tbChiTiet.getSelectionModel().addListSelectionListener(listener);
    }

    public void addTimKiemListener(ActionListener listener) {
        btnTimKiem.addActionListener(listener);
    }

    public String getKeyTimKiem() {
        return tfTimKiem.getText().trim();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDSDatTour;
    private javax.swing.JLabel lbNenDSDatTour;
    private javax.swing.JTable tbChiTiet;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
