/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import com.myctu.touristmanagementsystem.model.DangNhap;
import com.myctu.touristmanagementsystem.model.LocaleManager;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author GIGABYTE
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form loginView
     */
    public LoginView() {
//        System.out.println("Test");
        initComponents();
        this.setLocationRelativeTo(null);
//        this.setVisible(rootPaneCheckingEnabled);
        locale();
        revalidate();
        repaint();
        pack();
    }

    private ResourceBundle rb;

    private void locale() {
//        Locale.setDefault(locale); // Đặt locale mặc định
        try {
            rb = ResourceBundle.getBundle("com.myctu.touristmanagementsystem.properties.MyResources", LocaleManager.getCurrentLocale());
            System.out.println("Resource bundle loaded successfully.");
            setText(); // Cập nhật giao diện với ngôn ngữ mới
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
//        JComboBox<String> languageComboBox = new JComboBox<>(new String[]{"Tiếng Việt", "English"});
//        this.btnChange = languageComboBox;
    }

    private void setText() {
        lbDangNhap.setText(rb.getString("login"));
        lbTenDangNhap.setText(rb.getString("userName"));
        lbMatKhau.setText(rb.getString("pwd"));
        btnDangNhap.setText(rb.getString("login"));
        btnDangKy.setText(rb.getString("register"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTenDangNhap = new javax.swing.JLabel();
        lbMatKhau = new javax.swing.JLabel();
        pfMatKhau = new javax.swing.JPasswordField();
        tfTenDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lbDangNhap = new javax.swing.JLabel();
        btnChange = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("đăng nhập");
        setBackground(new java.awt.Color(233, 246, 233));
        setMinimumSize(new java.awt.Dimension(397, 252));
        setPreferredSize(new java.awt.Dimension(400, 255));
        setSize(new java.awt.Dimension(400, 255));

        lbTenDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTenDangNhap.setText("Tên đăng nhập");

        lbMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMatKhau.setText("Mật khẩu");

        pfMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pfMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMatKhauActionPerformed(evt);
            }
        });

        tfTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfTenDangNhap.setToolTipText("");

        btnDangNhap.setBackground(new java.awt.Color(163, 209, 255));
        btnDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnDangKy.setBackground(new java.awt.Color(163, 209, 255));
        btnDangKy.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng kí");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lbDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangNhap.setText("Đăng nhập");

        btnChange.setBackground(new java.awt.Color(241, 241, 241));
        btnChange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "English"}));
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnDangNhap)
                        .addGap(29, 29, 29)
                        .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenDangNhap)
                    .addComponent(tfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatKhau)
                    .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMatKhauActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
//        // TODO add your handling code here:
//        dispose();
//        ResgisterView res = new ResgisterView();
//        res.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        String selectedLanguage = (String) btnChange.getSelectedItem();
        if ("Tiếng Việt".equals(selectedLanguage)) {
            LocaleManager.setCurrentLocale(new Locale("vi", "VN"));
        } else if ("English".equals(selectedLanguage)) {
            LocaleManager.setCurrentLocale(new Locale("en", "US"));
        }
        locale();
    }//GEN-LAST:event_btnChangeActionPerformed

    private boolean validateLoginData(String tenDangNhap, String matKhau) {
        if (tenDangNhap == null || matKhau == null || tenDangNhap.isBlank() || matKhau.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được bỏ trống tên đăng nhập hoặc mật khấu!");
            return false;
        }
        return true;
    }

//DOC DU LIEU TU TEXTFILD
    public DangNhap getDangNhap() {
        String tenDangNhap = tfTenDangNhap.getText();
        System.out.println("Login view " + tenDangNhap);
        String matKhau = new String(pfMatKhau.getPassword());
//        System.out.println(matKhau);
        if (!validateLoginData(tenDangNhap, matKhau)) {
            return null;
        }
        DangNhap currentUser = new DangNhap(tenDangNhap, matKhau);

//        System.out.println("LoginView: " + matKhau);
        return currentUser;
    }

    public void addDangNhapListener(ActionListener listener) {
        btnDangNhap.addActionListener(listener);
    }

    public void addDangKyListener(ActionListener listener) {
        btnDangKy.addActionListener(listener);
    }

    public void addEnterActionListener(ActionListener listener) {
        pfMatKhau.addActionListener(listener);
        tfTenDangNhap.addActionListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btnChange;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel lbDangNhap;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JTextField tfTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
