/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import com.myctu.touristmanagementsystem.model.ChuDichVu;
import com.myctu.touristmanagementsystem.model.KhachDuLich;
import com.myctu.touristmanagementsystem.model.LocaleManager;
import com.myctu.touristmanagementsystem.model.NguoiDung;
import java.awt.event.ActionListener;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author GIGABYTE
 */
public class RegisterView extends javax.swing.JFrame {

    public static RegisterView getInstance() {
        return new RegisterView();
    }

    /**
     * Creates new form resgisterView
     */
    public RegisterView() {
        initComponents();
        this.setLocationRelativeTo(null);
        locale();
        rbtnKhachDuLich.setSelected(true);
    }

    private ResourceBundle rb;

    private void locale() {
//        Locale.setDefault(); // Đặt locale mặc định
        try {
            rb = ResourceBundle.getBundle("com.myctu.touristmanagementsystem.properties.MyResources", LocaleManager.getCurrentLocale());
            System.out.println("Resource bundle loaded successfully.");
            setText(); // Cập nhật giao diện với ngôn ngữ mới
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
//        JComboBox<String> languageComboBox = new JComboBox<>(new String[]{"Tiếng Việt", "English"});
//        this.btnChange = languageComboBox;
    }

    private void setText() {
        lbDangKy.setText(rb.getString("register"));
        lbHoVaTen.setText(rb.getString("full_name"));
        lbTenDangNhap.setText(rb.getString("username"));
        lbMatKhau.setText(rb.getString("password"));
        lbNhapLaiMatKhau.setText(rb.getString("confirm_password"));
        lbEmail.setText(rb.getString("email"));
        lbSoDienThoai.setText(rb.getString("phone")); 

        // Radio buttons
        rbtnChuDichVu.setText(rb.getString("service_owner"));
        rbtnKhachDuLich.setText(rb.getString("tourist")); 

        // Buttons
        btnDangKy.setText(rb.getString("register")); 
        btnHuy.setText(rb.getString("cancel_button")); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupVaiTro = new javax.swing.ButtonGroup();
        lbTenDangNhap = new javax.swing.JLabel();
        lbSoDienThoai = new javax.swing.JLabel();
        pfMatKhau = new javax.swing.JPasswordField();
        tfTenDangNhap = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        lbMatKhau = new javax.swing.JLabel();
        lbNhapLaiMatKhau = new javax.swing.JLabel();
        pfNhapLaiMatKhau = new javax.swing.JPasswordField();
        tfSoDienThoai = new javax.swing.JTextField();
        rbtnChuDichVu = new javax.swing.JRadioButton();
        rbtnKhachDuLich = new javax.swing.JRadioButton();
        lbDangKy = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lbHoVaTen = new javax.swing.JLabel();
        tfHoVaTen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí");
        setBackground(new java.awt.Color(102, 102, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        setIconImage(getIconImage());

        lbTenDangNhap.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTenDangNhap.setText("Tên đăng nhập");

        lbSoDienThoai.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbSoDienThoai.setText("Số điện thoại");

        pfMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pfMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMatKhauActionPerformed(evt);
            }
        });

        tfTenDangNhap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfTenDangNhap.setToolTipText("");
        tfTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenDangNhapActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(153, 204, 255));
        btnHuy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnDangKy.setBackground(new java.awt.Color(153, 204, 255));
        btnDangKy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng kí");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        lbMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbMatKhau.setText("Mật khẩu");

        lbNhapLaiMatKhau.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNhapLaiMatKhau.setText("Nhập lại mật khẩu");

        pfNhapLaiMatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pfNhapLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfNhapLaiMatKhauActionPerformed(evt);
            }
        });

        tfSoDienThoai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tfSoDienThoai.setToolTipText("");
        tfSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoDienThoaiActionPerformed(evt);
            }
        });

        btnGroupVaiTro.add(rbtnChuDichVu);
        rbtnChuDichVu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnChuDichVu.setText("Chủ dịch vụ");
        rbtnChuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnChuDichVuActionPerformed(evt);
            }
        });

        btnGroupVaiTro.add(rbtnKhachDuLich);
        rbtnKhachDuLich.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbtnKhachDuLich.setText("Khách du lịch");
        rbtnKhachDuLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnKhachDuLichActionPerformed(evt);
            }
        });

        lbDangKy.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbDangKy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDangKy.setText("Đăng kí");

        lbEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbEmail.setText("Email");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        lbHoVaTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbHoVaTen.setText("Họ và tên:");

        tfHoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoVaTenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbNhapLaiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnDangKy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuy))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbtnChuDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnKhachDuLich))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfMatKhau, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenDangNhap, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfNhapLaiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHoVaTen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenDangNhap))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatKhau))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNhapLaiMatKhau))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoDienThoai))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnChuDichVu)
                    .addComponent(rbtnKhachDuLich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMatKhauActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
//        // TODO add your handling code here:
//        dispose();
//        LoginView lg = new LoginView();
//        lg.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tfTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenDangNhapActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void pfNhapLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfNhapLaiMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfNhapLaiMatKhauActionPerformed

    private void tfSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoDienThoaiActionPerformed

    private void rbtnKhachDuLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnKhachDuLichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnKhachDuLichActionPerformed

    private void rbtnChuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnChuDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnChuDichVuActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfHoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoVaTenActionPerformed

    public boolean validateDangKy(String hoVaTen, String tenDangNhap, String sdt, String email) {
        if (hoVaTen == null || tenDangNhap == null || sdt == null || email == null) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống!");
            return false;
        }
        if (hoVaTen.isBlank() || tenDangNhap.isBlank() || sdt.isBlank() || email.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống!");
            return false;
        }
        return true;
    }

    public boolean validateMatKhau(String pwd, String confirmPwd) {
        if (pwd == null || pwd.isBlank() || confirmPwd == null || confirmPwd.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống mật khẩu");
            return false;
        }
        if (!(confirmPwd.equals(pwd))) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp !");
            return false;
        }
        return true;
    }

    //DOC DU LIEU TU TEXTFILD
    public NguoiDung getDangKy() {
        String hoVaTen = tfHoVaTen.getText().trim();
        String tenDangNhap = tfTenDangNhap.getText().trim();
        String matKhau = new String(pfMatKhau.getPassword());
        String nhapLaiMatKhau = new String(pfNhapLaiMatKhau.getPassword());
        String email = tfEmail.getText().trim();
        String sdt = tfSoDienThoai.getText().trim();
        String vaiTro;
        if (!validateDangKy(hoVaTen, tenDangNhap, sdt, email)) {
            return null;
        }
        if (!validateMatKhau(matKhau, nhapLaiMatKhau)) {
            return null;
        }
        if (rbtnChuDichVu.isSelected()) {
            vaiTro = "chudichvu";
            return new ChuDichVu(hoVaTen, tenDangNhap, matKhau, email, sdt, vaiTro);
        } else {
            vaiTro = "khachdulich";
            return new KhachDuLich(hoVaTen, tenDangNhap, matKhau, email, sdt, vaiTro);
        }
    }

    public void addDangKyListener(ActionListener listener) {
        btnDangKy.addActionListener(listener);
    }

    public void addHuyListener(ActionListener listener) {
        btnHuy.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.ButtonGroup btnGroupVaiTro;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel lbDangKy;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHoVaTen;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbNhapLaiMatKhau;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenDangNhap;
    private javax.swing.JPasswordField pfMatKhau;
    private javax.swing.JPasswordField pfNhapLaiMatKhau;
    private javax.swing.JRadioButton rbtnChuDichVu;
    private javax.swing.JRadioButton rbtnKhachDuLich;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfHoVaTen;
    private javax.swing.JTextField tfSoDienThoai;
    private javax.swing.JTextField tfTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
