/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;
import com.myctu.touristmanagementsystem.controller.ThanhToanController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GIGABYTE
 */
public class ThanhToanView extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToanView
     */
    public ThanhToanView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tbThongTinDichVuThanhToan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnXacNhanDatVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbThongTinDichVuThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "địa điểm", "ngày", "giá vé", "số lượng", "thành tiền"
            }
        ));
        jScrollPane4.setViewportView(tbThongTinDichVuThanhToan);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin đặt vé");

        btnXacNhanDatVe.setText("xác nhận đặt vé");
        btnXacNhanDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanDatVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(btnXacNhanDatVe)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnXacNhanDatVe)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanDatVeActionPerformed
        // TODO add your handling code here:
//            DonHangController donHangController = new DonHangController();
//    donHangController.xuLyXacNhanDatVe();
        ThanhToanController thanhToanController = new ThanhToanController();
        thanhToanController.btnXacNhanDatVeActionPerformed(this);
    
    }//GEN-LAST:event_btnXacNhanDatVeActionPerformed
  
    
    
    
    
    
    // Phương thức để nhận dữ liệu từ UserView
public void copyDataToThanhToanTable(DefaultTableModel modelDaDat) {
    DefaultTableModel modelThanhToan = (DefaultTableModel) tbThongTinDichVuThanhToan.getModel();

    // Sao chép dữ liệu 
    for (int i = 0; i < modelDaDat.getRowCount(); i++) {
        Object[] rowData = new Object[modelDaDat.getColumnCount()];

        for (int j = 0; j < modelDaDat.getColumnCount(); j++) {
            rowData[j] = modelDaDat.getValueAt(i, j);
        }

        // Thêm dữ liệu vào bảng tbThongTinDichVuThanhToan
        modelThanhToan.addRow(rowData);
    }
        System.out.println("du lieu da dc sao cheo sang ban thanh toan thanh cong");
//    JOptionPane.showMessageDialog(this, "Dữ liệu đã được sao chép sang bảng thanh toán thành công.");
}

    
    
    
public javax.swing.JTable getTbThongTinDichVuThanhToan() {
    return tbThongTinDichVuThanhToan;
}
    
    
    
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhanDatVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbThongTinDichVuThanhToan;
    // End of variables declaration//GEN-END:variables
}
