/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.myctu.touristmanagementsystem.view;

import com.myctu.touristmanagementsystem.dao.ThongKeDAO;
import com.myctu.touristmanagementsystem.model.LocaleManager;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.Map;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class ThongKeBaoCao extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeBaoCao
     */
    public ThongKeBaoCao() {
        initComponents();
        locale();
        pnShowDoanhThu.validate();
    }

    private ResourceBundle rb;

    private void locale() {
//        Locale.setDefault(); // Đặt locale mặc định
        try {
            rb = ResourceBundle.getBundle("com.myctu.touristmanagementsystem.properties.MyResources", LocaleManager.getCurrentLocale());
            System.out.println("Resource bundle loaded successfully.");
            setText();
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
    }

    private void setText() {
        try {
            btnShow.setText(rb.getString("showRevenue"));
            lbSumRev.setText(rb.getString("sumRev"));
            lbSumTourist.setText(rb.getString("sumTourist"));
            btnCapNhap.setText(rb.getString("update"));
        } catch (MissingResourceException e) {
            System.err.println("Error loading resource bundle: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSumRev = new javax.swing.JLabel();
        lbSumTourist = new javax.swing.JLabel();
        txt_TongDanhThu = new javax.swing.JTextField();
        txt_TongKhachDuLich = new javax.swing.JTextField();
        btnCapNhap = new javax.swing.JButton();
        pnShowThongKeBaoCao = new javax.swing.JPanel();
        btnShow = new javax.swing.JButton();
        pnShowDoanhThu = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(239, 246, 246));
        setDoubleBuffered(false);
        setPreferredSize(new java.awt.Dimension(1200, 650));

        lbSumRev.setText("Tổng doanh thu:");

        lbSumTourist.setText("Tổng khách du lịch:");

        txt_TongDanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TongDanhThuActionPerformed(evt);
            }
        });

        btnCapNhap.setBackground(new java.awt.Color(51, 153, 255));
        btnCapNhap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhap.setText("câp nhập");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        pnShowThongKeBaoCao.setBackground(new java.awt.Color(255, 255, 255));
        pnShowThongKeBaoCao.setLayout(new java.awt.BorderLayout());

        btnShow.setBackground(new java.awt.Color(51, 153, 255));
        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        pnShowDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnShowDoanhThu.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(316, Short.MAX_VALUE)
                        .addComponent(lbSumRev)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TongDanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(300, Short.MAX_VALUE)
                        .addComponent(lbSumTourist)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TongKhachDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(537, 537, 537))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnShowDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(pnShowThongKeBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TongKhachDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSumTourist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnShowThongKeBaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSumRev)
                            .addComponent(txt_TongDanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCapNhap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnShowDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TongDanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TongDanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TongDanhThuActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // TODO add your handling code here:
//        System.out.println("Chao");
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        ThongKeDAO model = new ThongKeDAO();
        Map<String, Integer> touristData = model.getTouristStatisticsByMonth("4");
        Map<String, Double> revenueData = model.getRevenueStatisticsByMonth("4");
        show(touristData, revenueData);
        pnShowDoanhThu.validate();


    }//GEN-LAST:event_btnShowActionPerformed

    public void addCapNhapListener(ActionListener listener) {
        System.out.println("hiiiiiiiiiiiii");
        btnCapNhap.addActionListener(listener);
    }

    // Phương thức này sẽ được controller gọi để hiển thị dữ liệu
    public void displayThongKeData(int tongSoLuongDat, double tongSoTien) {
        txt_TongDanhThu.setText(String.valueOf(tongSoTien));
        txt_TongKhachDuLich.setText(String.valueOf(tongSoLuongDat));
        System.out.println("Dữ liệu đã được cập nhật lên view: Tổng số lượng = " + tongSoLuongDat + ", Tổng số tiền = " + tongSoTien);
    }

    public void show(Map<String, Integer> touristData, Map<String, Double> revenueData) {
        DefaultCategoryDataset touristDataset = new DefaultCategoryDataset();
        for (Map.Entry<String, Integer> entry : touristData.entrySet()) {
            touristDataset.addValue(entry.getValue(), "Số lượng khách", entry.getKey());
        }
        JFreeChart touristChart = ChartFactory.createBarChart(
                "Thống kê số lượng khách theo tháng",
                "Thời gian",
                "Số lượng khách",
                touristDataset
        );

        CategoryPlot barChrt = touristChart.getCategoryPlot();
        // Tùy chỉnh màu đường lưới ngang       
        barChrt.setRangeGridlinePaint(Color.ORANGE);

        pnShowThongKeBaoCao.removeAll();
        pnShowThongKeBaoCao.add(new ChartPanel(touristChart));
        pnShowThongKeBaoCao.validate();
        pnShowThongKeBaoCao.repaint();

        DefaultCategoryDataset revenueDataset = new DefaultCategoryDataset();
        for (Map.Entry<String, Double> entry : revenueData.entrySet()) {
            revenueDataset.addValue(entry.getValue(), "Doanh thu (VND)", entry.getKey());
        }
        JFreeChart revenueChart = ChartFactory.createBarChart(
                "Thống kê doanh thu theo tháng",
                "Thời gian",
                "Doanh thu (VND)",
                revenueDataset
        );
        pnShowDoanhThu.removeAll();
        pnShowDoanhThu.add(new ChartPanel(revenueChart));
        pnShowDoanhThu.validate();
        pnShowThongKeBaoCao.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnShow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSumRev;
    private javax.swing.JLabel lbSumTourist;
    private javax.swing.JPanel pnShowDoanhThu;
    private javax.swing.JPanel pnShowThongKeBaoCao;
    private javax.swing.JTextField txt_TongDanhThu;
    private javax.swing.JTextField txt_TongKhachDuLich;
    // End of variables declaration//GEN-END:variables
}
